---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/example.yml

# EXAMPLE SKYTAP ANSIBLE PLAYBOOK
# ===============================
# Copyright (c) 2016 Ben Coleman
# Software provided under the terms of the Apache 2.0 license http://www.apache.org/licenses/LICENSE-2.0.txt


###################################################################################
### Example of using Skytap templates and common actions on them
###################################################################################

  tasks:
  - name: List templates
    skytap_template: action=list username={{api_user}} token={{api_token}}
    register: list_result

  - name: Save environment as template
    skytap_template: action=create environment_id={{environment_id}} name='New template' username={{api_user}} token={{api_token}}
    register: new_template

  - name: Rename template
    skytap_template: action=modify template_id={{new_template.api_result.id}} name='My template' username={{api_user}} token={{api_token}}

  - name: Change owner
    skytap_template: action=modify template_id={{new_template.api_result.id}} owner_id={{user_id}} username={{api_user}} token={{api_token}}

  - name: Copy template
    skytap_template: action=copy template_id={{new_template.api_result.id}} owner_id={{user_id}} name='Copied template' username={{api_user}} token={{api_token}}

  - name: Delete orginal new template
    skytap_template: action=delete template_id={{new_template.api_result.id}} username={{api_user}} token={{api_token}} 
